-- Run this in your Supabase SQL Editor.
-- Browser reads use the public anon key, so Row Level Security stays enabled.

create table if not exists public.plans (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    badge text not null,
    description text not null,
    price integer not null check (price >= 0),
    price_subtitle text not null default '1 Year Full Access',
    image_url text not null,
    image_alt text,
    features jsonb not null default '[]'::jsonb,
    accent_color text,
    featured boolean not null default false,
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    plan_slug text,
    plan_name text not null,
    price integer not null check (price >= 0),
    source text not null check (source in ('buy_now', 'whatsapp')),
    status text not null default 'new',
    created_at timestamptz not null default now()
);

alter table public.plans enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read active plans" on public.plans;
create policy "Public can read active plans"
on public.plans
for select
using (is_active = true);

drop policy if exists "Public can create order intents" on public.orders;
create policy "Public can create order intents"
on public.orders
for insert
with check (status = 'new');

insert into public.plans (
    name,
    slug,
    badge,
    description,
    price,
    price_subtitle,
    image_url,
    image_alt,
    features,
    accent_color,
    featured,
    is_active,
    sort_order
) values
(
    'Standard',
    'standard',
    'Standard Plan',
    'Perfect for individual creators',
    3000,
    '1 Year Full Access',
    'adobe standard.jpg',
    'Adobe Standard plan',
    '[
        "Photoshop & Lightroom 20+ Apps",
        "10000 AI Credits Per Month",
        "Premiere Pro & After Effects",
        "100GB Cloud Storage",
        "Stock Library Access",
        "Email Support"
    ]'::jsonb,
    null,
    false,
    true,
    1
),
(
    'Pro Plus',
    'pro-plus',
    'Most Popular',
    'For professional teams',
    3350,
    '1 Year Full Access',
    'adobe pro plus.jpg',
    'Adobe Pro Plus plan',
    '[
        "All Standard Features",
        "FireFly Video Generations",
        "4000 AI Credits Per Month",
        "1TB Cloud Storage",
        "Advanced AI Features(Nano Banana)",
        "Priority Support 24/7"
    ]'::jsonb,
    null,
    true,
    true,
    2
),
(
    'Canva Pro',
    'canva-pro',
    'Best Value',
    'Design like a pro',
    199,
    '1 Year Full Access',
    'pngwing.com.png',
    'Canva Pro',
    '[
        "100+ Million Premium Assets",
        "Remove Backgrounds Instantly",
        "Magic Resize & Animation",
        "All Fonts",
        "Premium Templates",
        "Official license"
    ]'::jsonb,
    '#7C3AED',
    false,
    true,
    3
)
on conflict (slug) do update set
    name = excluded.name,
    badge = excluded.badge,
    description = excluded.description,
    price = excluded.price,
    price_subtitle = excluded.price_subtitle,
    image_url = excluded.image_url,
    image_alt = excluded.image_alt,
    features = excluded.features,
    accent_color = excluded.accent_color,
    featured = excluded.featured,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    updated_at = now();

-- Feedback Table Setup
create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    email text not null,
    phone text not null,
    rating integer check (rating >= 1 and rating <= 5),
    comments text,
    created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Public can create feedback" on public.feedback;
create policy "Public can create feedback"
on public.feedback
for insert
with check (true);

